export const ROUTER = {
  HOME:'*',
  DANG_NHAP:'/dang-nhap',
  DANG_KY:'/dang-ky',
  DA_LUU:'/da-luu',
  THE_LOAI:{
    PHIM_TRUNG:'/the-loai/phim-trung-quoc',
    PHIM_MY:'/the-loai/phim-au-my',
    PHIM_HANH_DONG:'/the-loai/phim-hanh-dong',
    PHIM_PHIEU_LUU:'/the-loai/phim-phieu-luu',
    PHIM_TAM_LY:'/the-loai/phim-tam-ly',
    PHIM_VIEN_TUONG:'/the-loai/phim-vien-tuong',
    PHIM_HINH_SU:'/the-loai/phim-hinh-su',
    PHIM_AM_NHAC:'/the-loai/phim-am-nhac',
    PHIM_LE:'/the-loai/phim-le',
    PHIM_TINH_CAM:'/the-loai/phim-tinh-cam',
    HOAT_HINH:'/the-loai/hoat-hinh' 
  }
};